# -*- coding: utf-8 -*-
"""
/***************************************************************************
 KMeans
                                 A QGIS plugin
 This plugin is a minimal plugin that uses K-Means algorithm to group locations based in features.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-12-16
        copyright            : (C) 2020 by Luis González
        email                : luisgonromero@correo.ugr.es
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load KMeans class from file KMeans.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .KM import KMeans
    return KMeans(iface)
